name = "HomogeneousManifoldTesting"
uuid = "2e3a63ff-42bb-41f7-bba7-87d26dc597a2"
authors = ["Claire Brécheteau"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
